### ISSUE TITLE
Criação de tags

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/wiki#2]
## Descrição

Será necessário para a organização do projeto a criação de tags que abrangem as issues. Facilitando a organização e o entendimento. As tags devem seguir um padrão mostrado a seguir 

## Como fazer:
- A tag da issue deve ter nome em **português**
- A descrição deve ser em **português**
## Exemplo 
- Para issues que envolvem discussão e decisões do grupo a tag **discussão** seria uma boa escolha tag

**Comment by WelisonR** [comment]
Como a disciplina vai tá sendo separada em dinâmicas e seminários, acredito que seria uma boa fazer tais _labels_, ex.: **"dinâmica e seminário I"**. Poderia haver tags de **"iniciativa extra", "ambiente", "padronização"**, etc.

**Comment by bielrossi15** [comment]
Primeiras labels foram criadas, se necessário, adicionar mais conforme o andamento do projeto.
