### ISSUE TITLE
Escolha do tema

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/wiki#3]
## Sugestões

As sugestões de tema devem ser deixadas nos comentários dessa issue. Com base nas sugestões será escolhido um tema definitivo para o projeto.

**Comment by darmsDD** [comment]
###  **A Monitoria** 

### Problema
Todos os semestres da UnB inicia-se o processo de monitoria, porém a maioria das vezes ele é realizado por um formulário google que não possui muitas opções nem muita interatividade com o usuário, além de ter que receber a mesma informação do aluno todas as vezes que ele deseja se inscrever.

### Possível solução
Sabendo que o processo de monitoria é basicamente igual todos os semestres, um facilitador desse processo seria um app que tivesse para a parte aluno:
- Um sistema de login com as informações do usuário(como matrícula,nome etc) que são sempre pedidas;
- Uma lista das matérias que possuem monitoria e seus respectivos horários;
- Um esquema de marcar a matéria que deseja monitorar e suas segundas escolhas;
- Um timer de inicio de inscrição que pode ser iniciado durante o período de matrícula para quando as aulas começarem já terem monitores ou pelos menos o processo estar em um etapa mais avançada do que anteriormente.

Para a parte professor outras partes são necessárias como:
- Poder colocar as matérias que está ministrando e seus horários;
- Dar preferência de monitoria aos alunos que preferir e tiverem aprovação do conselho de monitoria.

Obs.: Existe a necessidade de entender por completo o processo de monitoria, principalmente as partes de aprovação de um aluno para a monitoria e a monitoria remunerada, por isso não há comentários sobre estas ainda.

**Comment by gustavolima00** [comment]
# UnB spotted
A ideia seria uma adaptação do existente UnB spotted

## O que é o UnB spotted?
Originalmente o UnB spotted consiste em usuários enviando fotos com declarações para pessoas na faculdade, as fotos são disponíveis para os seguidores das paginas ou membros dos grupos UnB spotted no Instagram e Facebook e Twitter. Quem deseja realizar uma declaração envia as fotos para os responsáveis por publica-la, e usuários que desejam acompanhar as declarações para saber se está entre os contemplados apenas seguem a página e acompanham.

## O que será feito de diferente? 
A ideia principal do app seria similar ao que existe hoje. As fotos deixariam de utilizar as plataformas das redes sociais e seriam armazenado em um serviço que as publica. Outra ideia que aumentaria o alcance dos usuários aos seus "spotteds" seria a realização de um reconhecimento facial da pessoa, e a busca do seu rosto em todo o banco de dados de imagens, filtrando as publicações que muitas vezes não são acompanhadas de um nome.

**Comment by gustavolima00** [comment]
# Sistema de doações

## Problemática

Existem várias comunidades carente que precisam periodicamente de doações de dinheiro, alimento e roupas. Além disso muitas coisas jogadas hoje no lixo são potencias objetos para doação. Por falta de conhecimento várias pessoas deixam de doar roupas usadas para jogar fora. Além disso várias pessoas, igrejas e organizações tem disposição de doar recursos para ajudar pessoas carentes.

## Contexto do sistema

A ideia geral do sistema é fazer publicações solicitando doações de itens específicos, como roupas, dinheiro, brinquedo... Com isso pessoas que tem várias itens que não irão utilizar mais podem entrar no app e filtrar suas buscas pelo tipo de item, e até por localidade, para encontrar quem está mais perto e necessita de doações.

**Comment by andrelucax** [comment]
# Plataforma de Perguntas
A ideia seria uma plataforma para que professores e monitores colocassem perguntas.

## Problemática
Varios professores hoje sao carentes de questoes para determinados assuntos, muitas vezes apenas as questoes de livros nao sao suficientes para disponibilizar um vasto aprendizado para os alunos, outras seria necessario juntar questoes de varios autores para um melhor aprendizado. Olhando pelo lado do alunos necessitam de questoes respondidas em um maior nivel de detalhes para auxiliar seu aprendizado.

## Ideia do sistema
Para solucionar esse problema uma ideia seria criar um sistema que armazena questoes respondidas e as classifica pelo conteudo. Deixando assim mais facil para um aluno que deseja aprofundar seu conhecimento por area e para professores que desejam ajudar seus alunos com questoes variadas. As questoes seriam avaliadas pela comunidade no topico dificuldade auxiliando ainda mais na pesquisa e as respostas e detalhamento de como chegar nelas seriam ocultadas ate o aluno por conta propria desejar ver.

**Comment by Ridersk** [comment]
# FreeLancer App

## Problema

Muitos alunos na Faculdade apenas estudam pois não possuem tempo para um emprego formal ou não conseguem estágio que possua um horário flexível que possa convergir com sua grade horária de disciplinas desejadas para o semestre. Porém com essa situação, inviabiliza que esses alunos consigam adquirir experiências desejáveis, ou até mesmo conseguir uma grana para suas necessidades. Dada essa situação esse aluno precisaria recorrer a outros métodos com trabalhos independentes, como freelance por exemplo.  
Uma outra dificuldade que pode atrapalhar os objetivos dessa pessoa, ela não possue um network para encontrar times que necessitam de apoio, ou seu network entre conhecidos não compartilham os mesmos objetivos, tecnologias, área de atuação etc.

## Possível Solução

O FreeLancer App assume o papel de uma espécie de “Rede de Network” ou “Rede Social de Trabalhos Independentes”, em que ajuda tanto individuos quanto times interessados podem ter uma maneira facilitada de se “encontrarem”. O Aplicativo também poderia facilitar que pessoas que possuem interesses parecidos se juntem para criarem uma possível startup futuramente.

### Funcionalidades Gerais:

Sistema de Recomendação inteligente tanto de “Freelancers” para times interessados quanto vice-versa.
Histórico de times que um freelancer já participou
Criação de uma network ou rede de relacionamentos com times ou freelancers
Integração com o Github para a geração automática e customizável de um “mini portifólio” no próprio App.
Com a integração com Github pode ser possível realizar uma importação da grade de contribuições no github, para extrair informações úteis, como quantidade de projetos ou times que um freelancer participou em uma semana, mês, ano… ; frequência de contribuições e tecnologias mais utilizadas.
Um perfil pessoal para os “Freelancers”, que mostre suas áreas de atuação, conhecimentos em tecnologias, interesses e aspirações pessoais.
Uma espécie de “Linha do Tempo” ou “Newsletter” Global do app com as principais iniciativas que estão acontecendo, seja eventos promovidos por times, seleção de novos freelancers etc…
A mesma funcionalidade anterior só que, voltada para compartilhamentos de sua network pessoal.
(Talvez possa quebrar o foco inicial) Módulo Separado para criação de um painel interativo(pessoal ou visivel a todos) em que o individuo pode criar campos de qualquer assunto, como estimativas e medições reais de horas trabalhadas em funcionalidades, custos estimados e reais, ou qualquer outra coisa que o indivíduo queira comparar para a geração de gráficos entre o estimado e o real, taxa de sucesso/fracasso, gênero do campo para gerar listar os gêneros em que o individuo possue mais sucesso ou precisa melhorar.

### Tecnologias:

Não sei bem se esse app se enquadraria melhor em um app mobile em que o usuários poderiam ter a flexibilidade de uso a qualquer momento, ou dado a complexidade do usuário ter que criar um perfil com um portifólio, o que talvez perderia um pouco a usabilidade na edição do mesmo seria melhor a criação de um sistema web para o uso em Desktop.# FreeLancer App

## Problema

	Muitos alunos na Faculdade apenas estudam pois não possuem tempo para um emprego formal ou não conseguem estágio que possua um horário flexível que possa convergir com sua grade horária de disciplinas desejadas para o semestre. Porém com essa situação, inviabiliza que esses alunos consigam adquirir experiências desejáveis, ou até mesmo conseguir uma grana para suas necessidades. Dada essa situação esse aluno precisaria recorrer a outros métodos com trabalhos independentes, como freelance por exemplo.
Uma outra dificuldade que pode atrapalhar os objetivos dessa pessoa, ela não possue um network para encontrar times que necessitam de apoio, ou seu network entre conhecidos não compartilham os mesmos objetivos, tecnologias, área de atuação etc.

## Possível Solução

	O FreeLancer App assume o papel de uma espécie de “Rede de Network” ou “Rede Social de Trabalhos Independentes”, em que ajuda tanto individuos quanto times interessados podem ter uma maneira facilitada de se “encontrarem”. O Aplicativo também poderia facilitar que pessoas que possuem interesses parecidos se juntem para criarem uma possível startup futuramente.

### Funcionalidades Gerais:

Sistema de Recomendação inteligente tanto de “Freelancers” para times interessados quanto vice-versa.
Histórico de times que um freelancer já participou
Criação de uma network ou rede de relacionamentos com times ou freelancers
Integração com o Github para a geração automática e customizável de um “mini portifólio” no próprio App.
Com a integração com Github pode ser possível realizar uma importação da grade de contribuições no github, para extrair informações úteis, como quantidade de projetos ou times que um freelancer participou em uma semana, mês, ano… ; frequência de contribuições e tecnologias mais utilizadas.
Um perfil pessoal para os “Freelancers”, que mostre suas áreas de atuação, conhecimentos em tecnologias, interesses e aspirações pessoais.
Uma espécie de “Linha do Tempo” ou “Newsletter” Global do app com as principais iniciativas que estão acontecendo, seja eventos promovidos por times, seleção de novos freelancers etc…
A mesma funcionalidade anterior só que, voltada para compartilhamentos de sua network pessoal.
(Talvez possa quebrar o foco inicial) Módulo Separado para criação de um painel interativo(pessoal ou visivel a todos) em que o individuo pode criar campos de qualquer assunto, como estimativas e medições reais de horas trabalhadas em funcionalidades, custos estimados e reais, ou qualquer outra coisa que o indivíduo queira comparar para a geração de gráficos entre o estimado e o real, taxa de sucesso/fracasso, gênero do campo para gerar listar os gêneros em que o individuo possue mais sucesso ou precisa melhorar.

### Tecnologias:

Não sei bem se esse app se enquadraria melhor em um app mobile em que o usuários poderiam ter a flexibilidade de uso a qualquer momento, ou dado a complexidade do usuário ter que criar um perfil com um portifólio, o que talvez perderia um pouco a usabilidade na edição do mesmo seria melhor a criação de um sistema web para o uso em Desktop.

**Comment by Ridersk** [comment]
# FreeLancer App

## Problema

Muitos alunos na Faculdade apenas estudam pois não possuem tempo para um emprego formal ou não conseguem estágio que possua um horário flexível que possa convergir com sua grade horária de disciplinas desejadas para o semestre. Porém com essa situação, inviabiliza que esses alunos consigam adquirir experiências desejáveis, ou até mesmo conseguir uma grana para suas necessidades. Dada essa situação esse aluno precisaria recorrer a outros métodos com trabalhos independentes, como freelance por exemplo.  
Uma outra dificuldade que pode atrapalhar os objetivos dessa pessoa, ela não possue um network para encontrar times que necessitam de apoio, ou seu network entre conhecidos não compartilham os mesmos objetivos, tecnologias, área de atuação etc.

## Possível Solução

O FreeLancer App assume o papel de uma espécie de “Rede de Network” ou “Rede Social de Trabalhos Independentes”, em que ajuda tanto individuos quanto times interessados podem ter uma maneira facilitada de se “encontrarem”. O Aplicativo também poderia facilitar que pessoas que possuem interesses parecidos se juntem para criarem uma possível startup futuramente.

### Funcionalidades Gerais:

* Sistema de Recomendação inteligente tanto de “Freelancers” para times interessados quanto vice-versa.
Histórico de times que um freelancer já participou
* Criação de uma network ou rede de relacionamentos com times ou freelancers
* Integração com o Github para a geração automática e customizável de um “mini portifólio” no próprio App.
* Com a integração com Github pode ser possível realizar uma importação da grade de contribuições no github, para extrair informações úteis, como quantidade de projetos ou times que um freelancer participou em uma semana, mês, ano… ; frequência de contribuições e tecnologias mais utilizadas.
* Um perfil pessoal para os “Freelancers”, que mostre suas áreas de atuação, conhecimentos em tecnologias, interesses e aspirações pessoais.
* Uma espécie de “Linha do Tempo” ou “Newsletter” Global do app com as principais iniciativas que estão acontecendo, seja eventos promovidos por times, seleção de novos freelancers etc…
* A mesma funcionalidade anterior só que, voltada para compartilhamentos de sua network pessoal.
* (Talvez possa quebrar o foco inicial) Módulo Separado para criação de um painel interativo(pessoal ou visivel a todos) em que o individuo pode criar campos de qualquer assunto, como estimativas e medições reais de horas trabalhadas em funcionalidades, custos estimados e reais, ou qualquer outra coisa que o indivíduo queira comparar para a geração de gráficos entre o estimado e o real, taxa de sucesso/fracasso, gênero do campo para gerar listar os gêneros em que o individuo possue mais sucesso ou precisa melhorar.

### Tecnologias:

Não sei bem se esse app se enquadraria melhor em um app mobile em que o usuários poderiam ter a flexibilidade de uso a qualquer momento, ou dado a complexidade do usuário ter que criar um perfil com um portifólio, o que talvez perderia um pouco a usabilidade na edição do mesmo seria melhor a criação de um sistema web para o uso em Desktop.# FreeLancer App

**Comment by WelisonR** [comment]
Após muita análise pelo grupo, decidiu-se que a aplicação "a monitoria" será o tema desenvolvido na disciplina de Desenho e Arquitetura de Software. A metodologia e a justificativa para a escolha do tema poderá ser consultada brevemente acessando o [gh-pages](https://2019-2-arquitetura-desenho.github.io/wiki/) no tópico de "dinâmica e seminário I".
