### ISSUE TITLE
Definição de Tecnologias

### ISSUE THREAD

**Issue by WelisonR** [2019-2-arquitetura-desenho/wiki#8]
## Descrição
A atual issue tem por objetivo discutir sobre as **tecnologias pertinentes ao desenvolvimento do projeto**. Tem-se como base os artefatos gerados e definidos até o presente momento, verificáveis [aqui](https://2019-2-arquitetura-desenho.github.io/wiki/dinamica_seminario_I/Elicitacao/questionario/).

## Informações
* A aplicação desenvolvida será **web**.
* Há a possibilidade de reutilizar código para conseguir a oferta do matrícula web. Analisar [MWScanner](https://github.com/ads-unigrade-2019-1/MWScanner).

## Repositório

* Como deve ser organizado o repositório? Por exemplo, um repositório para o backend, outro pro frontend, etc? Mesmo repositório? Por quê?
* Quais os módulos de trabalho?

## Tecnologias

* Qual tecnologia principal do frontend? Por quê?
* Qual tecnologia principal do backend? Por quê?
* Qual a tecnologia de banco de dados? (A priori, ver se é possível utilizar a solução do grupo do MWScanner feita em mongoDB)
* Sugestões de CI/CD? Bibliotecas, frameworks ou outras ferramentas de suporte?

**Comment by bielrossi15** [comment]
# Repositório
- Divisão: Creio que a divisão deve ser feita entre front e back, para poder trabalhar em ambos sem interferência.

# Tecnologias
- Frontend: ReactJS, pois o time possui conhecimento e é uma framework muito rápida de pegar o ritmo.
- Backend: DjangoREST, pois o ideal seria montar uma API REST pra fazer as requisições e utilizar python seria ótimo, pois utilizaremos um leitor de PDF.
- Banco: MongoDB pois é padrão do MWscanner.

**Comment by PauloVitorRocha** [comment]
Concordo com o @bielrossi15. Pórem talvez teriamos dificuldade para adaptar o MongoDB pois o BD padrão do DjangoREST é o SQLite.

**Comment by gustavolima00** [comment]
Concordo com o @bielrossi15  também, Python e djangoREST são tecnologias conhecidas pelos membros da equipe, o desenvolvimento se torna mais confortável. E boa parte da equipe tem experiência com javascript, o que deixa o ReactJS um pouco mais fácil de aprender para quem ainda não tem experiência.

**Comment by darmsDD** [comment]
A ideia de @bielrossi15 é boa, e acredito que podemos utiliza-lá. Algo que fortalece essa ideia é que foi mencionado anteriormente pelo @bielrossi15  em conversar anteriores que algumas partes essenciais do projeto, como leitura de pdf, tem suporte nas tecnologias mencionadas e assim isso facilitará o desenvolvimento do projeto.

**Comment by bielrossi15** [comment]
Para extração de PDF, existem algumas libs em python que eu acho que deviam ser estudadas para a escolha, sendo elas:
- [PDFMiner](http://www.unixuser.org/~euske/python/pdfminer/index.html)
- [PyPDF2](https://github.com/colemana/PyPDF2)

Se alguém souber de mais alguma, por favor comentar.
